[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "commence_py"
version = "0.1.0"
description = "warapper for Commence Rm"
dependencies = [
    "pywin32",
]


[tool.mypy]
files = "src/**/*.py"
ignore_missing_imports = true
strict = true
mypy_path = "stubs"

[tool.ruff]
line-length = 100
fix = true
show-fixes = true
show-source = true
src = ["src", "test"]
exclude = ["src/commence_py/cmc_dde.py"]

[tool.ruff.lint]
extend-select = [
    "UP", # pyupgrade
    "E", # pycodestyle
    "W", # pycodestyle warnings
    "E501", # line length
]

[tool.ruff.format]
quote-style = "single"