[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "commence_py"
version = "0.1.0"
description = "warapper for Commence Rm"
dependencies= [
    "pywin32",
]