[project]
name = "pycommence"
version = "0.1.0"
description = "wrapper for Commence Rm via pywin32"
authors = [
    { name = "PawRequest", email = "pycommence+pawrequest@users.noreply.github.com" }
]
dependencies = [
    "pywin32",
    "loguru",
    "pydantic",
]
readme = "README.md"
requires-python = ">= 3.10"

[project.optional-dependencies]
dev = [
    "pytest",
]
doc = [
    "sphinx",
    "sphinx-autodoc-typehints",
    "sphinx-autodoc2",
    "sphinx-rtd-theme",
    "sphinx-readme",
    "myst-parser",
    "sphinx_rtd_dark_mode",

]
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = false
dev-dependencies = [
    "pytest",
]

[tool.hatch.metadata]
allow-direct-references = true
