name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Build Sphinx Documentation
        run: |
          sphinx-build -E -a -b html ./docs_source/ ./build/html


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
